- id: cmake-format
  name: cmake-format
  description: Formats CMake files.
  entry: cmake_format_pre_commit_hook --in-place
  language: python
  types: [file, text]
  files: '^(CMake.*|.*\.cmake.*)$'
