-   id: cmake-format
    name: cmake-format
    entry: cmake-format
    language: python
    'files': ^(CMake.*|.*\.cmake.*)$
    args: ["-i"]
    require_serial: false
    additional_dependencies: []
