-   id: cmake-format
    name: cmake-format
    description: Formats CMake list files.
    entry: cmake-format
    language: python
    files: (CMakeLists.*|.*\.cmake|.*\.cmake.in)$
    args: ["-i"]
    require_serial: false
    additional_dependencies: []
